#before:
#  hooks:
#    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X sub2clash/config.Version={{ .Version }}
    no_unique_dist_dir: true
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"